(** Tests for PDB hash functions.

    Test vectors validated against LLVM's hashStringV1 implementation. *)

let test_hash_empty () =
  (* Empty string: no XOR iterations, result = 0 |= 0x20202020
     then the mixing steps *)
  let h = Pdb.Hash.hash_string_v1 "" in
  Alcotest.(check bool) "empty string hash is deterministic" true (h <> 0)

let test_hash_short_strings () =
  (* Hash should be deterministic *)
  let h1 = Pdb.Hash.hash_string_v1 "a" in
  let h2 = Pdb.Hash.hash_string_v1 "a" in
  Alcotest.(check int) "same string same hash" h1 h2;
  let h3 = Pdb.Hash.hash_string_v1 "b" in
  (* Different strings should (very likely) produce different hashes *)
  Alcotest.(check bool) "different strings different hash" true (h1 <> h3)

let test_hash_four_byte_aligned () =
  (* Exactly 4 bytes: one full u32 XOR, no remainder *)
  let h = Pdb.Hash.hash_string_v1 "abcd" in
  Alcotest.(check bool) "4-byte hash is nonzero" true (h <> 0)

let test_hash_remainder_two_bytes () =
  (* 6 bytes: 1 full u32 + 2 byte remainder *)
  let h = Pdb.Hash.hash_string_v1 "abcdef" in
  Alcotest.(check bool) "6-byte hash is nonzero" true (h <> 0)

let test_hash_remainder_one_byte () =
  (* 5 bytes: 1 full u32 + 1 byte remainder *)
  let h = Pdb.Hash.hash_string_v1 "abcde" in
  Alcotest.(check bool) "5-byte hash is nonzero" true (h <> 0)

let test_hash_remainder_three_bytes () =
  (* 7 bytes: 1 full u32 + 2 byte + 1 byte remainder *)
  let h = Pdb.Hash.hash_string_v1 "abcdefg" in
  Alcotest.(check bool) "7-byte hash is nonzero" true (h <> 0)

let test_hash_known_values () =
  (* The toLowerMask (0x20202020) means the hash maps upper/lowercase
     to the same value. Verify this property. *)
  let h_lower = Pdb.Hash.hash_string_v1 "main" in
  let h_upper = Pdb.Hash.hash_string_v1 "MAIN" in
  Alcotest.(check int) "case insensitive" h_lower h_upper

let test_hash_long_string () =
  (* A longer string exercises multiple u32 XOR iterations *)
  let h = Pdb.Hash.hash_string_v1 "/names" in
  Alcotest.(check bool) "/names hash is nonzero" true (h <> 0)

let test_hash_to_lower_mask () =
  (* The toLowerMask ensures bit 5 of each byte is always set.
     This means the result always has 0x20202020 set. *)
  let h = Pdb.Hash.hash_string_v1 "test" in
  (* After the mixing steps, this property may not hold for the final value,
     but the intermediate result before mixing has it. *)
  Alcotest.(check bool) "hash produces reasonable value" true (h > 0)

(** Exact value tests against LLVM's hashStringV1 reference implementation.
    Values generated by compiling LLVM's Hash.cpp algorithm in C. *)

let test_hash_exact_empty () =
  Alcotest.(check int) "\"\"" 0x20240400 (Pdb.Hash.hash_string_v1 "")

let test_hash_exact_main () =
  Alcotest.(check int) "\"main\"" 0x6E64C225 (Pdb.Hash.hash_string_v1 "main")

let test_hash_exact_names () =
  Alcotest.(check int) "\"/names\"" 0x6D6CFC21
    (Pdb.Hash.hash_string_v1 "/names")

let test_hash_exact_linkinfo () =
  Alcotest.(check int) "\"/LinkInfo\"" 0x282209ED
    (Pdb.Hash.hash_string_v1 "/LinkInfo")

let test_hash_exact_a () =
  Alcotest.(check int) "\"a\"" 0x20240441 (Pdb.Hash.hash_string_v1 "a")

let test_hash_exact_ab () =
  Alcotest.(check int) "\"ab\"" 0x20244649 (Pdb.Hash.hash_string_v1 "ab")

let test_hash_exact_abc () =
  Alcotest.(check int) "\"abc\"" 0x2024460A (Pdb.Hash.hash_string_v1 "abc")

let test_hash_exact_abcd () =
  Alcotest.(check int) "\"abcd\"" 0x646F8A62
    (Pdb.Hash.hash_string_v1 "abcd")

let test_hash_exact_case_insensitive () =
  (* "MAIN" must produce the exact same hash as "main" *)
  Alcotest.(check int) "\"MAIN\"" 0x6E64C225 (Pdb.Hash.hash_string_v1 "MAIN")

let test_hash_exact_int () =
  Alcotest.(check int) "\"int\"" 0x20244A14 (Pdb.Hash.hash_string_v1 "int")

let test_hash_exact_point () =
  Alcotest.(check int) "\"Point\"" 0x6E64CC6D
    (Pdb.Hash.hash_string_v1 "Point")

let test_hash_exact_unique_name () =
  Alcotest.(check int) "\".?AUPoint@@\"" 0x3B2F6E43
    (Pdb.Hash.hash_string_v1 ".?AUPoint@@")

(** Exact CRC32/JamCRC values (hash_buffer_v8), validated against C reference. *)

let test_crc32_empty () =
  Alcotest.(check int) "crc32 empty" 0x00000000 (Pdb.Hash.hash_buffer_v8 "")

let test_crc32_a () =
  Alcotest.(check int) "crc32 a" 0x3AB551CE (Pdb.Hash.hash_buffer_v8 "a")

let test_crc32_abc () =
  Alcotest.(check int) "crc32 abc" 0xCA6598D0 (Pdb.Hash.hash_buffer_v8 "abc")

let test_crc32_123456789 () =
  Alcotest.(check int) "crc32 123456789" 0x2DFD2D88
    (Pdb.Hash.hash_buffer_v8 "123456789")

let () =
  Alcotest.run "PDB Hash"
    [
      ( "hash_string_v1",
        [
          Alcotest.test_case "empty" `Quick test_hash_empty;
          Alcotest.test_case "short strings" `Quick test_hash_short_strings;
          Alcotest.test_case "4-byte aligned" `Quick test_hash_four_byte_aligned;
          Alcotest.test_case "2-byte remainder" `Quick
            test_hash_remainder_two_bytes;
          Alcotest.test_case "1-byte remainder" `Quick
            test_hash_remainder_one_byte;
          Alcotest.test_case "3-byte remainder" `Quick
            test_hash_remainder_three_bytes;
          Alcotest.test_case "known values" `Quick test_hash_known_values;
          Alcotest.test_case "long string" `Quick test_hash_long_string;
          Alcotest.test_case "toLowerMask" `Quick test_hash_to_lower_mask;
        ] );
      ( "exact_values",
        [
          Alcotest.test_case "empty" `Quick test_hash_exact_empty;
          Alcotest.test_case "main" `Quick test_hash_exact_main;
          Alcotest.test_case "/names" `Quick test_hash_exact_names;
          Alcotest.test_case "/LinkInfo" `Quick test_hash_exact_linkinfo;
          Alcotest.test_case "a" `Quick test_hash_exact_a;
          Alcotest.test_case "ab" `Quick test_hash_exact_ab;
          Alcotest.test_case "abc" `Quick test_hash_exact_abc;
          Alcotest.test_case "abcd" `Quick test_hash_exact_abcd;
          Alcotest.test_case "MAIN" `Quick test_hash_exact_case_insensitive;
          Alcotest.test_case "int" `Quick test_hash_exact_int;
          Alcotest.test_case "Point" `Quick test_hash_exact_point;
          Alcotest.test_case ".?AUPoint@@" `Quick test_hash_exact_unique_name;
        ] );
      ( "crc32",
        [
          Alcotest.test_case "empty" `Quick test_crc32_empty;
          Alcotest.test_case "a" `Quick test_crc32_a;
          Alcotest.test_case "abc" `Quick test_crc32_abc;
          Alcotest.test_case "123456789" `Quick test_crc32_123456789;
        ] );
    ]
