(** Integration tests: parse real PDB files generated by llvm-pdbutil yaml2pdb.

    These tests validate our parser against PDB files produced by LLVM, which is
    the reference implementation. *)

let fixture_path name =
  let dir = Sys.getcwd () in
  (* When run via dune, cwd is _build/default/test/integration *)
  let candidates =
    [
      Filename.concat dir (Filename.concat "../../test/fixtures" name);
      Filename.concat dir (Filename.concat "../fixtures" name);
      Filename.concat dir (Filename.concat "test/fixtures" name);
    ]
  in
  match List.find_opt Sys.file_exists candidates with
  | Some p -> p
  | None ->
      (* Try project root *)
      let p =
        Filename.concat (Filename.concat dir "../../../../test/fixtures") name
      in
      if Sys.file_exists p then p
      else failwith (Printf.sprintf "Fixture %s not found (cwd=%s)" name dir)

let open_pdb name =
  let path = fixture_path name in
  let buf = Object.Buffer.parse path in
  Pdb.Msf.read buf

(** {2 MSF structure tests} *)

let test_msf_summary () =
  let msf = open_pdb "simple.pdb" in
  let sb = Pdb.Msf.superblock msf in
  Alcotest.(check int) "block size" 4096 (Unsigned.UInt32.to_int sb.block_size);
  Alcotest.(check bool) "has streams" true (Pdb.Msf.stream_count msf > 0);
  (* simple.pdb has 9 streams per llvm-pdbutil *)
  Alcotest.(check int) "stream count" 9 (Pdb.Msf.stream_count msf)

(** {2 PDB Info Stream tests} *)

let test_pdb_info_stream () =
  let msf = open_pdb "simple.pdb" in
  let stream = Pdb.Msf.get_stream_exn msf 1 in
  let cur = Object.Buffer.cursor stream in
  let info = Pdb.Pdb_stream.read cur in
  (* VC70 version *)
  Alcotest.(check int)
    "version" 20000404
    (Pdb.Pdb_stream.pdb_version_to_int info.version);
  Alcotest.(check int) "age" 1 (Unsigned.UInt32.to_int info.age);
  (* Should have named streams including /names *)
  Alcotest.(check bool)
    "has /names" true
    (List.exists (fun (n, _) -> n = "/names") info.named_streams);
  (* Should have ContainsIdStream feature *)
  Alcotest.(check bool)
    "has ContainsIdStream" true
    (List.mem Pdb.Pdb_stream.ContainsIdStream info.features)

(** {2 TPI Stream tests} *)

let test_tpi_stream () =
  let msf = open_pdb "simple.pdb" in
  let stream = Pdb.Msf.get_stream_exn msf 2 in
  let cur = Object.Buffer.cursor stream in
  let header = Pdb.Tpi.parse_header cur in
  Alcotest.(check int)
    "type index begin" 0x1000
    (Unsigned.UInt32.to_int header.type_index_begin);
  Alcotest.(check int) "7 type records" 7 (Pdb.Tpi.num_type_records header);
  let records = Pdb.Tpi.parse_type_records cur header in
  let record_list = List.of_seq records in
  Alcotest.(check int) "parsed 7 records" 7 (List.length record_list);
  (* 0x1000: LF_ARGLIST with 0 args *)
  (match List.nth record_list 0 with
  | Pdb.Codeview_types.ArgList { args } ->
      Alcotest.(check int) "arglist 0 args" 0 (Array.length args)
  | _ -> Alcotest.fail "0x1000: expected ArgList");
  (* 0x1001: LF_PROCEDURE returning int (0x0074), 0 params *)
  (match List.nth record_list 1 with
  | Pdb.Codeview_types.Procedure { return_type; param_count; _ } ->
      Alcotest.(check int)
        "procedure return type" 0x0074
        (Unsigned.UInt32.to_int (Pdb.Type_index.to_u32 return_type));
      Alcotest.(check int) "procedure params" 0 param_count
  | _ -> Alcotest.fail "0x1001: expected Procedure");
  (* 0x1002: LF_STRUCTURE "Point" (forward ref) *)
  (match List.nth record_list 2 with
  | Pdb.Codeview_types.Structure { name; properties; _ } ->
      Alcotest.(check string) "fwd ref name" "Point" name;
      Alcotest.(check bool) "is forward ref" true properties.fwdref
  | _ -> Alcotest.fail "0x1002: expected Structure");
  (* 0x1003: LF_FIELDLIST with 2 members (x, y) *)
  (match List.nth record_list 3 with
  | Pdb.Codeview_types.FieldList { members } -> (
      Alcotest.(check int) "fieldlist members" 2 (List.length members);
      (match List.nth members 0 with
      | Pdb.Codeview_types.Member { name; offset; _ } ->
          Alcotest.(check string) "member 0 name" "x" name;
          Alcotest.(check int64) "member 0 offset" 0L offset
      | _ -> Alcotest.fail "expected Member");
      match List.nth members 1 with
      | Pdb.Codeview_types.Member { name; offset; _ } ->
          Alcotest.(check string) "member 1 name" "y" name;
          Alcotest.(check int64) "member 1 offset" 4L offset
      | _ -> Alcotest.fail "expected Member")
  | _ -> Alcotest.fail "0x1003: expected FieldList");
  (* 0x1004: LF_STRUCTURE "Point" (complete, size=8) *)
  (match List.nth record_list 4 with
  | Pdb.Codeview_types.Structure { name; properties; size; field_count; _ } ->
      Alcotest.(check string) "complete name" "Point" name;
      Alcotest.(check bool) "not forward ref" false properties.fwdref;
      Alcotest.(check int64) "size" 8L size;
      Alcotest.(check int) "field count" 2 field_count
  | _ -> Alcotest.fail "0x1004: expected Structure");
  (* 0x1005: LF_FIELDLIST with 3 enumerators *)
  (match List.nth record_list 5 with
  | Pdb.Codeview_types.FieldList { members } -> (
      Alcotest.(check int) "enum fieldlist" 3 (List.length members);
      (match List.nth members 0 with
      | Pdb.Codeview_types.Enumerate { name; value; _ } ->
          Alcotest.(check string) "enum 0" "RED" name;
          Alcotest.(check int64) "enum 0 val" 0L value
      | _ -> Alcotest.fail "expected Enumerate");
      match List.nth members 2 with
      | Pdb.Codeview_types.Enumerate { name; value; _ } ->
          Alcotest.(check string) "enum 2" "BLUE" name;
          Alcotest.(check int64) "enum 2 val" 2L value
      | _ -> Alcotest.fail "expected Enumerate")
  | _ -> Alcotest.fail "0x1005: expected FieldList");
  (* 0x1006: LF_ENUM "Color" *)
  match List.nth record_list 6 with
  | Pdb.Codeview_types.Enum { name; field_count; _ } ->
      Alcotest.(check string) "enum name" "Color" name;
      Alcotest.(check int) "enum count" 3 field_count
  | _ -> Alcotest.fail "0x1006: expected Enum"

(** {2 IPI Stream tests} *)

let test_ipi_stream () =
  let msf = open_pdb "simple.pdb" in
  let stream = Pdb.Msf.get_stream_exn msf 4 in
  let cur = Object.Buffer.cursor stream in
  let header = Pdb.Tpi.parse_header cur in
  Alcotest.(check int) "2 IPI records" 2 (Pdb.Tpi.num_type_records header);
  let records = Pdb.Tpi.parse_type_records cur header in
  let record_list = List.of_seq records in
  Alcotest.(check int) "parsed 2 records" 2 (List.length record_list);
  (* 0x1000: LF_FUNC_ID "main" *)
  (match List.nth record_list 0 with
  | Pdb.Codeview_types.FuncId { name; func_type; _ } ->
      Alcotest.(check string) "func_id name" "main" name;
      Alcotest.(check int)
        "func_id type" 0x1001
        (Unsigned.UInt32.to_int (Pdb.Type_index.to_u32 func_type))
  | _ -> Alcotest.fail "0x1000: expected FuncId");
  (* 0x1001: LF_STRING_ID "simple.c" *)
  match List.nth record_list 1 with
  | Pdb.Codeview_types.StringId { str; _ } ->
      Alcotest.(check string) "string_id" "simple.c" str
  | _ -> Alcotest.fail "0x1001: expected StringId"

(** {2 DBI Stream tests} *)

let test_dbi_stream () =
  let msf = open_pdb "simple.pdb" in
  let stream = Pdb.Msf.get_stream_exn msf 3 in
  let cur = Object.Buffer.cursor stream in
  let dbi = Pdb.Dbi.parse cur in
  Alcotest.(check int) "1 module" 1 (Array.length dbi.modules);
  Alcotest.(check string) "module name" "simple.obj" dbi.modules.(0).module_name;
  Alcotest.(check string)
    "obj file name" "simple.obj" dbi.modules.(0).obj_file_name

(** {2 Complex fixture tests (inheritance, virtual methods, multiple modules)} *)

let test_complex_tpi () =
  let msf = open_pdb "complex.pdb" in
  let stream = Pdb.Msf.get_stream_exn msf 2 in
  let cur = Object.Buffer.cursor stream in
  let header = Pdb.Tpi.parse_header cur in
  Alcotest.(check int) "15 type records" 15 (Pdb.Tpi.num_type_records header);
  let records = List.of_seq (Pdb.Tpi.parse_type_records cur header) in
  Alcotest.(check int) "parsed 15" 15 (List.length records);
  (* 0x1000: LF_ARGLIST with 2 args *)
  (match List.nth records 0 with
  | Pdb.Codeview_types.ArgList { args } ->
      Alcotest.(check int) "arglist count" 2 (Array.length args)
  | _ -> Alcotest.fail "0x1000: expected ArgList");
  (* 0x1002: Base forward ref *)
  (match List.nth records 2 with
  | Pdb.Codeview_types.Structure { name; properties; _ } ->
      Alcotest.(check string) "Base fwd" "Base" name;
      Alcotest.(check bool) "is fwdref" true properties.fwdref
  | _ -> Alcotest.fail "0x1002: expected Structure");
  (* 0x1003: LF_VTSHAPE with 2 entries *)
  (match List.nth records 3 with
  | Pdb.Codeview_types.VTShape { descriptors } ->
      Alcotest.(check int) "vtshape count" 2 (Array.length descriptors)
  | _ -> Alcotest.fail "0x1003: expected VTShape");
  (* 0x1006: LF_MFUNCTION (void Base::vfunc) *)
  (match List.nth records 6 with
  | Pdb.Codeview_types.MFunction { return_type; class_type; param_count; _ } ->
      Alcotest.(check int) "mfunc ret" 3
        (Unsigned.UInt32.to_int (Pdb.Type_index.to_u32 return_type));
      Alcotest.(check int) "mfunc class" 0x1002
        (Unsigned.UInt32.to_int (Pdb.Type_index.to_u32 class_type));
      Alcotest.(check int) "mfunc params" 0 param_count
  | _ -> Alcotest.fail "0x1006: expected MFunction");
  (* 0x1008: Base field list with VFuncTab, Member, 2x OneMethod *)
  (match List.nth records 8 with
  | Pdb.Codeview_types.FieldList { members } ->
      Alcotest.(check int) "base fieldlist" 4 (List.length members);
      (match List.nth members 0 with
      | Pdb.Codeview_types.VFuncTab _ -> ()
      | _ -> Alcotest.fail "base[0]: expected VFuncTab");
      (match List.nth members 1 with
      | Pdb.Codeview_types.Member { name; offset; _ } ->
          Alcotest.(check string) "base member" "value" name;
          Alcotest.(check int64) "base member offset" 8L offset
      | _ -> Alcotest.fail "base[1]: expected Member");
      (match List.nth members 2 with
      | Pdb.Codeview_types.OneMethod { name; _ } ->
          Alcotest.(check string) "base onemethod" "vfunc" name
      | _ -> Alcotest.fail "base[2]: expected OneMethod")
  | _ -> Alcotest.fail "0x1008: expected FieldList");
  (* 0x1009: Base complete -- size=16, vtable_shape=0x1003 *)
  (match List.nth records 9 with
  | Pdb.Codeview_types.Structure { name; size; vtable_shape; _ } ->
      Alcotest.(check string) "Base complete" "Base" name;
      Alcotest.(check int64) "Base size" 16L size;
      Alcotest.(check int) "Base vtshape" 0x1003
        (Unsigned.UInt32.to_int (Pdb.Type_index.to_u32 vtable_shape))
  | _ -> Alcotest.fail "0x1009: expected Structure");
  (* 0x100B: Derived field list with BaseClass, Member, OneMethod *)
  (match List.nth records 11 with
  | Pdb.Codeview_types.FieldList { members } ->
      Alcotest.(check int) "derived fieldlist" 3 (List.length members);
      (match List.nth members 0 with
      | Pdb.Codeview_types.BaseClass { base_type; offset; _ } ->
          Alcotest.(check int) "bclass type" 0x1002
            (Unsigned.UInt32.to_int (Pdb.Type_index.to_u32 base_type));
          Alcotest.(check int64) "bclass offset" 0L offset
      | _ -> Alcotest.fail "derived[0]: expected BaseClass");
      (match List.nth members 1 with
      | Pdb.Codeview_types.Member { name; offset; _ } ->
          Alcotest.(check string) "derived member" "extra" name;
          Alcotest.(check int64) "derived member offset" 16L offset
      | _ -> Alcotest.fail "derived[1]: expected Member")
  | _ -> Alcotest.fail "0x100B: expected FieldList");
  (* 0x100C: Derived complete -- size=24 *)
  (match List.nth records 12 with
  | Pdb.Codeview_types.Structure { name; size; _ } ->
      Alcotest.(check string) "Derived complete" "Derived" name;
      Alcotest.(check int64) "Derived size" 24L size
  | _ -> Alcotest.fail "0x100C: expected Structure");
  (* 0x100E: enum Color *)
  match List.nth records 14 with
  | Pdb.Codeview_types.Enum { name; field_count; _ } ->
      Alcotest.(check string) "enum" "Color" name;
      Alcotest.(check int) "enum count" 3 field_count
  | _ -> Alcotest.fail "0x100E: expected Enum"

let test_complex_ipi () =
  let msf = open_pdb "complex.pdb" in
  let stream = Pdb.Msf.get_stream_exn msf 4 in
  let cur = Object.Buffer.cursor stream in
  let header = Pdb.Tpi.parse_header cur in
  Alcotest.(check int) "4 IPI records" 4 (Pdb.Tpi.num_type_records header);
  let records = List.of_seq (Pdb.Tpi.parse_type_records cur header) in
  (* LF_FUNC_ID "main" *)
  (match List.nth records 0 with
  | Pdb.Codeview_types.FuncId { name; _ } ->
      Alcotest.(check string) "func_id" "main" name
  | _ -> Alcotest.fail "IPI 0: expected FuncId");
  (* LF_STRING_ID "complex.cpp" *)
  (match List.nth records 1 with
  | Pdb.Codeview_types.StringId { str; _ } ->
      Alcotest.(check string) "string_id" "complex.cpp" str
  | _ -> Alcotest.fail "IPI 1: expected StringId");
  (* LF_UDT_SRC_LINE for Base at line 3 *)
  (match List.nth records 2 with
  | Pdb.Codeview_types.UdtSrcLine { line; _ } ->
      Alcotest.(check int) "Base line" 3 (Unsigned.UInt32.to_int line)
  | _ -> Alcotest.fail "IPI 2: expected UdtSrcLine");
  (* LF_UDT_SRC_LINE for Derived at line 12 *)
  match List.nth records 3 with
  | Pdb.Codeview_types.UdtSrcLine { line; _ } ->
      Alcotest.(check int) "Derived line" 12 (Unsigned.UInt32.to_int line)
  | _ -> Alcotest.fail "IPI 3: expected UdtSrcLine"

let test_complex_dbi () =
  let msf = open_pdb "complex.pdb" in
  let stream = Pdb.Msf.get_stream_exn msf 3 in
  let cur = Object.Buffer.cursor stream in
  let dbi = Pdb.Dbi.parse cur in
  Alcotest.(check int) "2 modules" 2 (Array.length dbi.modules);
  Alcotest.(check string) "module 0" "complex.obj"
    dbi.modules.(0).module_name;
  Alcotest.(check string) "module 1" "* Linker *"
    dbi.modules.(1).module_name

let () =
  Alcotest.run "PDB Integration"
    [
      ("msf", [ Alcotest.test_case "summary" `Quick test_msf_summary ]);
      ( "pdb_info",
        [ Alcotest.test_case "info stream" `Quick test_pdb_info_stream ] );
      ("tpi", [ Alcotest.test_case "type records" `Quick test_tpi_stream ]);
      ("ipi", [ Alcotest.test_case "id records" `Quick test_ipi_stream ]);
      ("dbi", [ Alcotest.test_case "dbi stream" `Quick test_dbi_stream ]);
      ( "complex",
        [
          Alcotest.test_case "TPI (inheritance+vtable)" `Quick
            test_complex_tpi;
          Alcotest.test_case "IPI (udt_src_line)" `Quick test_complex_ipi;
          Alcotest.test_case "DBI (multiple modules)" `Quick test_complex_dbi;
        ] );
    ]
